[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "flask-caching>=2.3.1",
    "requests>=2.32.3",
    "textblob>=0.19.0",
]
